apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-sa
  namespace: kube-system
secrets:
- name: dev-role-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-full-access-role
  namespace: keycloak 
rules:
  - apiGroups: ["*"]  
    resources: ["*"]  
    verbs: ["*"]      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-full-access-binding
  namespace: keycloak
subjects:
  - kind: ServiceAccount
    name: dev-sa      
    namespace: kube-system
roleRef:
  kind: Role
  name: keycloak-full-access-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-role 
rules:
  - apiGroups: [""]  
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]  

  - apiGroups: [""] 
    resources: ["pods"]
    verbs: ["*"] 

  - apiGroups: ["apps"]  
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]  

  - apiGroups: ["batch"]  
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]  #

  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]  

  - apiGroups: [""]  
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["networking.k8s.io"] 
    resources: ["ingressclasses"]
    verbs: ["get", "list", "watch"] 

  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create"] 

  - apiGroups: [""] 
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]  

  - apiGroups: ["storage.k8s.io"] 
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]  

  - apiGroups: [""] 
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]  

  - apiGroups: [""] 
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 

  - apiGroups: ["helm.k8s.io"]
    resources: ["charts"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["helm.k8s.io"]
    resources: ["releases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-role-binding
subjects:
- kind: ServiceAccount
  name: dev-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: dev-role
  apiGroup: rbac.authorization.k8s.io
