apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany  # Allows multiple nodes to mount the volume
  resources:
    requests:
      storage: 1Gi  # You can modify this size as needed
  storageClassName: openbs-nfs-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nfs-test
spec:
  replicas: 2  # Two replicas to test RWX (shared access across multiple pods)
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: nfs-volume
              mountPath: /usr/share/nginx/html  # Mount the NFS volume at this path
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-rwx-pvc  # Reference the PVC you created
